src/config/urls.py
from django.conf import settings

from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include ("django.contrib.auth.urls")),
    path('accounts/', include ("users.urls")),
    path("", include("core.urls"))
    #Local
    # path('home/', core_views.home),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, 
                            document_root=settings.MEDIA_ROOT)

src/core/urls.py
from django.urls import path

from .views import (PostsView,
					HomeView,
					PostCreateView,
)
app_name = 'core'

urlpatterns = [
	path('', HomeView.as_view(), name='home'),
	path('posts/', PostsView.as_view(), name='my_posts'),
	path('posts/create/', PostCreateView.as_view(), name='post_creation'),

]

src/users/urls.py
from django.urls import path
from .views import SignupView, UserSettingsView



app_name = 'users'

urlpatterns = [
    path('signup/', 
            SignupView.as_view(), 
            name='signup'),
    
    path('settings/', 
            UserSettingsView.as_view(), 
            name='settings'),
]

src/common/models.py
from django.db import models
from django.conf import settings


# STATICFILE_DIR = settings.STATICFILES_DIRS[0]
# UPLOAD_DIR = os.path.join(STATICFILE_DIR)

class Photo(models.Model):
    image = models.ImageField(upload_to="upload/images/")
    is_avatar = models.BooleanField(default=False)

src/core/models.py
from django.db import models
from django.contrib.auth import get_user_model
#from users.models import User

User = get_user_model()

class Post(models.Model):
    """User's post model"""
    title = models.CharField(max_length=45)
    body = models.TextField()
    image = models.ForeignKey("common.Photo", on_delete=models.CASCADE,
                            null=True,
                            blank = True)
                            
    is_active = models.BooleanField(default=True)

    poster = models.ForeignKey(User,
                                on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.poster}: {self.title}"

src/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class RolesData():
	'''Roles values for Role Model'''
	DEFAULT = 1
	MANAGER = 2
	ADMIN = 5

	ROLES_CHOICES = (
		(DEFAULT, 'user'),
		(MANAGER, 'manager'),
		(ADMIN, 'admin')
	)

class Role(models.Model):
    """Management roles for users"""
    # Move to RolesData


    id = models.PositiveSmallIntegerField(choices=RolesData.ROLES_CHOICES,
                                          primary_key=True)

    @classmethod
    def get_default_user_role(cls):
        role, created = cls.objects.get_or_create(id=RolesData.DEFAULT)
        return role.id

    def __str__(self):
        return self.get_id_display()


class User(AbstractUser):
	"""Custom User model"""
	phone_number = models.CharField(max_length=13)

	def __str__(self):
		#if self.first_name and self.last_name:
			#return f"{self.first_name} {self.last_name}"
		return self.username


class Profile(models.Model):
	first_name = models.CharField(max_length=45, null=True, blank=True)
	last_name = models.CharField(max_length=45, null=True, blank=True)

	avatar = models.OneToOneField("common.Photo", 
							on_delete=models.CASCADE, 
							null=True, 
							blank=True)
	
	user = models.OneToOneField('User',
							on_delete=models.CASCADE,
							null=True)
    
    # Move to Profile model
	role = models.ForeignKey('Role',
							default=Role.get_default_user_role,
							on_delete=models.DO_NOTHING)

	
	def __str__(self):
		if self.first_name and self.last_name:
			return f"{self.first_name} {self.last_name} | {self.role}"
		return f"{self.user.username} | {self.role}"

src/core/forms.py
from django import forms

from .models import Post


class PostCreationForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'body', 'image',)

    def save(self, user, *args, **kwargs):


        post = Post.objects.create(title=self.data.get('title'),
                                    body=self.data.get('body'),
                                    poster = user)
        if self.data.get('image'):
            post.image = self.data.get('image')

        return post

        

src/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms

from .models import User

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'phone_number')

class UserSettingsForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name')

    def save(self, commit=True, user=None):
        user.first_name = self.cleaned_data.get('first_name')
        user.last_name = self.cleaned_data.get('last_name')

        user.save()



    @staticmethod
    def __check_digit(word: str) -> bool:
        for letter in word:
            if letter.isdigit():
                return True     

    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)

    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')

        if not (self.__check_digit(first_name)):
            raise forms.ValidationError('First name must include at least 1 digit')

        return first_name


    def clean_last_name(self):
        last_name = self.cleaned_data.get('last_name')

        if not (self.__check_digit(last_name)):
            raise forms.ValidationError('Last name must include at least 1 digit')

        return last_name

src/core/views.py
from django.views.generic import ListView, CreateView, View
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect

from .models import Post
from .forms import PostCreationForm


class HomeView(ListView):
    template_name = 'core/index.html'
    #queryset = Post.objects.exclude(is_active=False, poster=self.request.user)

    def get_queryset(self, **kwargs):
        return Post.objects.exclude(is_active=False, poster=self.request.user)

    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('login')
        return super().get(request, *args, **kwargs)


class PostsView(ListView):
    """Posts view"""
    template_name = 'core/index.html'

    def get_queryset(self, **kwargs):
        """Returns active posters posts"""
        return Post.objects.filter(is_active=True,
                                   poster=self.request.user)

    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('login')
        return super().get(request, *args, **kwargs)

class PostCreateView(CreateView):
    '''Provides post creation by form'''
    template_name = 'core/post_creation.html'
    form_class = PostCreationForm
    model = Post

    def post(self, request, *args, **kwargs):
        form = PostCreationForm(data=request.POST)
        form.save(user=request.user)

        return redirect('core:my_posts')
           
    
    
    

src/users/views.py
from django.contrib.auth import get_user_model

from django.urls import reverse_lazy
from django.views.generic import CreateView, View
#from django.contrib.auth.forms import UserCreationForm
from django.template.response import TemplateResponse
from .forms import SignUpForm, UserSettingsForm

User = get_user_model()

class SignupView(CreateView):
    template_name = "registration/signup.html"
    form_class = SignUpForm
    success_url = reverse_lazy('login')

class UserSettingsView(View):
    template_name = 'users/settings.html'
    form_class = UserSettingsForm

    def get(self, request, *args, **kwargs):
        form = self.form_class()

        context = {
            'form': form
        }
        return TemplateResponse(request, 
        template=self.template_name,
        context=context
        )
    
    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)

        context = {
            'form': form
        }
        if form.is_valid():
            form.save(user=request.user)
            return TemplateResponse(request, 
                                    template=self.template_name,
                                    context=context)

        context['errors'] = form.errors
        return TemplateResponse(request,
                                template=self.template_name,
                                context=context)

templates/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>IT Step project</title>

    <!-- CSS only -->
    <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
            integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
            crossorigin="anonymous"
    />

    <!-- JS, Popper.js, and jQuery -->
    <script
            src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"
    ></script>
    <script
            src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
            integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
            crossorigin="anonymous"
    ></script>
    <script
            src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
            integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
            crossorigin="anonymous"
    ></script>

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>

<div class="header">
    <div class="header__left_side">
        <a href="{% url 'core:home' %}"><h1 class="header__title">IT Step Project</h1></a>
        <h2 class="header__about">About</h2>
    </div>
    {% if user.is_authenticated %}
        <h3 class="header__user">Hello, {{user}}</h3>
    {% else %}
        <div class="header__authentication">
            <a href="{% url 'login'%}">Login</a>
            <a href="{% url 'users:signup'%}">Signup</a>
        </div>
    {% endif %}
</div>

{% if user.is_authenticated %}
{% block content %}{% endblock content %}
{% else %}
{% block not_auth_content %}{% endblock not_auth_content %}
{% endif %}



</body>
</html>

templates/core/index.html
{% extends '_base.html' %} {% block content %}

<div class="wrapper">
  <div class="menu">
    <div class="menu__top">
      <img
        class="menu__img"
        src="{{user.profile.avatar.image.url}}"
        alt="My avatar"
      />
      <div class="menu__name">{{user}}</div>
      <ul class="menu__links">
        <a href="">
          <li class="menu__link">Friends</li>
        </a>
        <a href="{% url 'core:my_posts' %}">
          <li class="menu__link">Posts</li>
        </a>
        <a href="{% url 'core:home' %}">
          <li class="menu__link">News</li>
        </a>
      </ul>
    </div>

    <ul class="menu__bottom">
      <a href="{% url 'users:settings' %}"><li class="menu__bottom_item">Settings</li></a>
      <a href="{%url 'logout' %}"><li class="menu__bottom_item">Logout</li></a>
    </ul>
  </div>
</div>

<div class="content">
  {% for post in object_list %}
  <div class="card">
    <img src="{{post.image.image.url}}" class="card-img-top" alt="..." />
    <div class="card-body">
      <h5 class="card-title">{{post}}</h5>
      <p class="card-text">{{post.body}}</p>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock content %}

templates/core/post_creation.html
{% extends '_base.html' %} {% block content %}

<div class="wrapper">
  <div class="menu">
    <div class="menu__top">
      <img
        class="menu__img"
        src="{{user.profile.avatar.image.url}}"
        alt="My avatar"
      />
      <div class="menu__name">{{user}}</div>
      <ul class="menu__links">
        <a href="">
          <li class="menu__link">Friends</li>
        </a>
        <a href="{% url 'core:my_posts' %}">
          <li class="menu__link">Posts</li>
        </a>
        <a href="{% url 'core:home' %}">
          <li class="menu__link">News</li>
        </a>
      </ul>
    </div>

    <ul class="menu__bottom">
      <a href="{% url 'users:settings' %}"
        ><li class="menu__bottom_item">Settings</li></a
      >
      <a href="{%url 'logout' %}"><li class="menu__bottom_item">Logout</li></a>
    </ul>
  </div>
</div>

<div class="post__create">
  <form method="POST" action="">
    {% csrf_token %} {{form.as_p}}

    <button type="submit">Create post</button>
  </form>
</div>

{% endblock content %}

templates/users/settings.html
{% extends '_base.html' %}
{% block content %}


<div class="wrapper">
  <div class="menu">
    <div class="menu__top">
      <img
        class="menu__img"
        src="{{user.profile.avatar.image.url}}"
        alt="My avatar"
      />
      <div class="menu__name">{{user}}</div>
      <ul class="menu__links">
        <a href="">
          <li class="menu__link">Friends</li>
        </a>
        <a href="{% url 'core:my_posts' %}">
          <li class="menu__link">Posts</li>
        </a>
        <a href="{% url 'core:home' %}">
          <li class="menu__link">News</li>
        </a>
      </ul>
    </div>

    <ul class="menu__bottom">
      <a href="{% url 'users:settings' %}"><li class="menu__bottom_item">Settings</li></a>
      <a href="{%url 'logout' %}"><li class="menu__bottom_item">Logout</li></a>
    </ul>
  </div>
</div>


<div class='settings__initial_data'>
    <h1>First name: {{ user.first_name}}</h1>
    <h1>Last name: {{ user.last_name}}</h1>
</div>

<div class="user__settings">
    <form action="{% url 'users:settings'%}" method="POST" class='user__settings_form'>
        {% csrf_token %}

        {{ form.first_name.label}}
        {{ form.first_name}}

        {{ form.last_name.label}}
        {{ form.last_name}}

        <button type="submit">Save</button>
    </form>


<div class="messages">
    {% if errors %}
        {{ errors}}

    {% endif %}
</div>
</div>
{% endblock content %}

{% block not_auth %}
{% endblock not_auth %}